### ISSUE TITLE
Nagios 3 fails to configure

### ISSUE THREAD

**Issue by 4thAce** [jbreams/nagmq#28] opened 2015-04-29 22:12 UTC
I have Nagios 3.5.1 on Ubuntu 14.04.1. I tried

```
./configure --with-nagios3-headers=~/nagios/include
```

It gets past the libev.h and jansson.h dependencies but then fails to recognize our Nagios 3.5.1 header files.

```
checking icinga.h usability... no
checking icinga.h presence... no
checking for icinga.h... no
checking nagios/nagios.h usability... no
checking nagios/nagios.h presence... no
checking for nagios/nagios.h... no
checking nagios/lib/libnagios.h usability... no
checking nagios/lib/libnagios.h presence... no
checking for nagios/lib/libnagios.h... no
configure: error: in `/home/rmagahiz/nagmq':
configure: error: Must supply headers/source to Nagios - see the README requirements section.
See `config.log' for more details
$ ls ~/nagios/include
broker.h    common.h     downtime.h    locations.h.in  nagios.h        nebmodules.h  perfdata.h  snprintf.h.in
cgiauth.h   compat.h     epn_nagios.h  logging.h       nebcallbacks.h  nebstructs.h  shared.h    sretention.h
cgiutils.h  config.h     getcgi.h      macros.h        neberrors.h     netutils.h    skiplist.h  statusdata.h
comments.h  config.h.in  locations.h   Makefile        nebmods.h       objects.h     snprintf.h
```

I don't believe this is used in Nagios 3. I can get past this configure error if I download the Nagios 4.0.8 source and specify both --with-nagios3-headers and --with-nagios4-src, but then the make fails to find nebstructs.h

**Comment by jbreams** [comment] 2015-04-30 02:32
Hi, I think I have a typo that's causing this that should be fixed now. Can you try again?

**Comment by 4thAce** [comment] 2015-04-30 17:05
Thanks. I pulled and reran the same configure command but it failed with the same error messages including the ones about libnagios.h.
https://gist.github.com/4thAce/3fcd8c20c63bb4de66e2

**Comment by jbreams** [comment] 2015-05-02 17:00
Hi, I think we should be in business now. There were actually a bunch of nagios 3.x incompatibilities that snuck in over time that I've gone through and fixed. At least on my centos box, everything is working with nagios-3.5.1. Can you try it out now?

**Comment by 4thAce** [comment] 2015-05-04 19:18
I pulled it once more and it still hits the "Must supply headers/source to Nagios" error when checking nagios/lib/libnagios.h, which does not exist on this Ubuntu vm

**Comment by jbreams** [comment] 2015-05-04 21:23
I can't reproduce this. Did you run autoreconf after pulling? I just pushed a commit that definitely compiles on ubuntu 14.04, what version of ubuntu are you having the problem on? The configure command I used was `libev_CFLAGS=" " libev_LIBS="-lev" ./configure --with-nagios3-headers=/tmp/nagios/include` and I had built nagios 3.5.1 from source in /tmp.

**Comment by 4thAce** [comment] 2015-05-05 21:01
Oh, maybe that's it, I forgot. I'll give it another try soon

**Comment by 4thAce** [comment] 2015-05-07 18:34
It definitely got past that point. Now I see it complaining that libzmq is not found, though I have libzmq3 version 4.0.4+dfsg-2 installed (libzmq1 is version 2.2.0 and it requires 3.0 or later).

**Comment by jbreams** [comment] 2015-05-07 18:39
Do you have the dev package installed? It uses pkg-config to test whether zeromq is installed. If you run `pkg-config libzmq --lib --cflags`, is there any output?

**Comment by 4thAce** [comment] 2015-05-11 17:14
Thanks for the tip. I updated the packages and got the configure command to succeed. Now I'm looking at this error during 'make'
```
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../dnxmq    -I/home/rmagahiz/nagios/include -I/usr/local/include   -I/usr/local/include    -Werror=implicit-function-declaration -g -O2 -MT nagmq_la-nagmq_pull.lo -MD -MP -MF .deps/nagmq_la-nagmq_pull.Tpo -c -o nagmq_la-nagmq_pull.lo `test -f 'nagmq_pull.c' || echo './'`nagmq_pull.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../dnxmq -I/home/rmagahiz/nagios/include -I/usr/local/include -I/usr/local/include -Werror=implicit-function-declaration -g -O2 -MT nagmq_la-nagmq_pull.lo -MD -MP -MF .deps/nagmq_la-nagmq_pull.Tpo -c nagmq_pull.c  -fPIC -DPIC -o .libs/nagmq_la-nagmq_pull.o
nagmq_pull.c: In function 'process_ping':
nagmq_pull.c:45:2: error: implicit declaration of function 'gettimeofday' [-Werror=implicit-function-declaration]
  gettimeofday(&curtime, NULL);
  ^
cc1: some warnings being treated as errors
make[2]: *** [nagmq_la-nagmq_pull.lo] Error 1
```

**Closed** 2018-05-09 15:46 UTC
